### ISSUE TITLE
Remove the approval dashbaord view when the module is uninstalled

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_workflows#16]
Experincing an error when uninstalling and reinstalling localgov_workflows.
The view `localgov_approvals_dashboard` remains,

>   Configuration objects (views.view.localgov_approvals_dashboard) provided by localgov_workflows already exist in active configuration  

I don't think the view has much utility outside of localgov_workflows, so it should be uninstalled when the module is.

**Comment by stephen-cox** [comment]
Should be fixed with #19
