### ISSUE TITLE
Workflow: Allow editor to see the difference between versions sent for review

### ISSUE THREAD

**Issue by davidsiddall** [localgovdrupal/localgov_workflows#17]
As an Editor, I want to see the difference between revisions visually that have been sent for review, so that I can easily see what has changed and approve/reject accordingly.

**Comment by stephen-cox** [comment]
The Drupal [Diff](https://www.drupal.org/project/diff) module used to provide this sort of functionality in Drupal 7. Worth checking if it works for Drupal 8/9

**Comment by willguv** [comment]
@stephen-cox @davidsiddall 

We've installed Diff in Cumbria, and this looks to be very useful. I suggest we include this as default, or a suggested inclusion for councils

------
There's a conversation about this in Slack

https://localgovdrupal.slack.com/archives/C01TS349XCY/p1631187585001900

**Comment by finnlewis** [comment]
Add this to localgov profile or localgov_workflows?

**Comment by stephen-cox** [comment]
Pull request for this is ready for review #20 

It enables the Diff module and configures it to use the admin theme. Without the configuration to change the theme it uses the main site theme when viewing the differences between revisions, but this doesn't include styling for the Diff module and so looks terrible.

**Comment by finnlewis** [comment]
Nice one @stephen-cox  - works well for me. 

The choice of theme might be something to get some more opinions on. 

With the admin theme, the content does not render much like the published content.

![image](https://user-images.githubusercontent.com/326588/134205793-23029072-aa44-4617-87cd-642dd395f964.png)

With the default theme the content renders a bit more like reality, but not quite.

![image](https://user-images.githubusercontent.com/326588/134205630-d30ce46f-9fcc-48f0-b19d-96ec0e0e7104.png)

I wonder which content designers will prefer as a default? 

CC @benhillsjones @tom-steel @davidsiddall @msayoung

**Comment by stephen-cox** [comment]
We discussed this briefly at the content lifecycle working group and decided the admin theme works best for now.
