### ISSUE TITLE
Make workflow tab labels more clear

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_workflows#53]
I always struggle to explain the difference between these workflow tab labels to councils, which makes me suspect others are having problems

![Image](https://github.com/localgovdrupal/localgov_workflows/assets/708140/6417ce7f-b275-40ce-b75d-be26a84acaab)

- What does each one do?
- Do we need them all?

Separately, one council has mentioned this would be good to hide or disable as they don't use workflow. How easy it is to hide/ uninstall and what's the impact?

**Comment by willguv** [comment]
@davidsiddall wondering if you're still about? Would be great to catch up on this

**Comment by keelanfh** [comment]
Me too, people often ask me what "Moderated content" does and I have no idea what to say! 

In particular, in our setup there is never anything in the "Moderated content" tab. The message says

> No moderated content available. Only pending versions of content, such as drafts, are listed here.

but we have plenty of draft content which doesn't appear here, so I don't know what it's for.

**Comment by andybroomfield** [comment]
I belive its the Drupal workflow default view, possibly redundant as both approvals dashboard, shows content in draft that has been put in review, and needs review is the content that comes from the review date.

**Comment by andybroomfield** [comment]
Oddly enough, I just tried to disable the moderated content view thinking that would remove it, and instead a lot of draft content started showing instead!

**Comment by willguv** [comment]
@stephen-cox @msayoung can you remember what each of the workflow tabs do please? Am keen to review these labels and hide anything that's not needed. Thanks

**Comment by stephen-cox** [comment]
- 'Overview' is the main content view provided by core
- 'Moderated content' should show content that has a moderation state that is not published. This is provided by the core Content Moderation module.
- 'Approvals dashboard' shows content in the review moderation state.
- 'Needs review' shows content that with a review date that's in the past.

What looks to be confusing people is the core moderated content view isn't working as expected. It expects the core Editorial workflow, but we're not enabling this.

My suggestion is we disable this view if the Editorial workflow is not enabled. The alternative is to try and modify it so with works with the LGD workflow, but if this functionality is useful we could create our own view.

**Comment by keelanfh** [comment]
Sounds a sensible approach to me

**Comment by willguv** [comment]
Hi @stephen-cox yes, could we disable the moderated content view please

Is it straightforward to change the "approvals dashboard" and "needs review" tab labels - I think we can be more clear

**Comment by willguv** [comment]
I wonder if Overview / Approve / Expired works?

An alternative would be Overview / Approve / Review but the last two feel too similar and would need explanation

Thoughts welcome everyone!

**Comment by willguv** [comment]
Hi @stephen-cox let's go for

Overview/ Approve/ Review/ Locked (for the locked content view)

Thanks

**Comment by stephen-cox** [comment]
@willguv Just to update on this.

I have a branch that changes the labels. It turns out it's not really possible to remove the Moderated Content view as disabling the view then shows a basic listing that is coded into the Content Moderation module. It should be possible to just hide the tab, but I have added some code that fixes the view so it works with the LGD workflow.

Does this sound okay or would you still like to hide the tab even though the view now works as it should?

**Comment by willguv** [comment]
Hi @stephen-cox can I see somewhere what this new view provides? If it's not offering much my hunch is to hide it anyway

A screenshot would be fine. If you have to create a lot of content to make it meaningful, a description of what the view shows might be enough to make a decision on

Thanks for looking at this

**Comment by stephen-cox** [comment]
@willguv I've deployed the work on PR #66 to the test site. You can see the changes here: https://test.localgovdrupal.org/admin/content/

**Comment by willguv** [comment]
Hi @stephen-cox I've had a look now, thanks

1) 
The Moderated Content view doesn't seem to show anything useful - can you hide it please?

2)
I notice that there's empty state wording for Approve and Review - could this be changed?

For Approve "No content waiting for approval"

For Review "No content has passed its review date"

3)
(Happy to write another issue for this)

How does a content editor know without clicking on the Approve and Review tabs that there is content to approve or review? 

Does the tab show a number of items to approve, anything like that? 

Thanks for your hard work on this

**Comment by stephen-cox** [comment]
@willguv 

1. I should be able to remove the tab, but will have to check.
2. It's easy enough to this text to the views when there are no results
3. Users will have to click the tabs to find out. I don't think it's possible to add the number of items to the tabs as the text is cached by Drupal and getting around this will be problematic. The usual solution to this sort of thing is a dashboard that people land on which shows summary data for this sort of thing.

**Comment by stephen-cox** [comment]
Hi @willguv 

I have updated the message on the views when there are no results.

Removing the Content Moderation tab is problematic. I can do this for every install, but there are going to be councils that use this and so we only want to disable it for new installations.

As it stands things now look like:

![image](https://github.com/localgovdrupal/localgov_workflows/assets/7189914/9fd9ecf0-a59c-4111-b085-4b78d53ceec8)

![image](https://github.com/localgovdrupal/localgov_workflows/assets/7189914/1d257683-d799-4dd1-a72f-d294e0d9ec19)

![image](https://github.com/localgovdrupal/localgov_workflows/assets/7189914/0fe985b1-b015-45d3-9aa8-ff4bd931f92d)

**Comment by willguv** [comment]
Hi @stephen-cox is the moderated content tab hidden for new installations? Can we write instructions for councils to hide this? Thanks

**Comment by stephen-cox** [comment]
> is the moderated content tab hidden for new installations?

It's not. As mentioned it's easy to do this for all installations, but I'm not sure how to do this only for new installations as this is defined by core and is in code.

**Comment by willguv** [comment]
@stephen-cox just noticed on test that the empty state messages for Approve and Review haven't changed

Can you fix this please?

Approve currently says "No content waiting for approval. Only content in review is listed here." and should say "No content waiting for approval"

Review currently says "No content waiting for review." and should say "No content has passed its review date"

Thanks!

**Comment by willguv** [comment]
Chat with @andybroomfield at PG

Review tab is as expected (pages that have expired)

Approve tab includes pages to be checked from colleagues, and pages that have expired. From a Product POV the tab should just show the former, not the latter

What do we think about this?

**Comment by andybroomfield** [comment]
See #72 for details ref above comment.

**Comment by willguv** [comment]
Hi @stephen-cox this looks to be mostly done, thanks

The only thing that is missing is the name and order change for the "moderated content" tab

I thought we said:

- name should change to "Unpublished"
- tab should be the last one in the sequence (after "Review")

Are these easy changes to make? Happy to write another card if needed

**Comment by willguv** [comment]
@stephen-cox ignore me, just seen this is covered elsewhere. I'll close this
