### ISSUE TITLE
Rename/ move "moderated content" tab

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_workflows#71]
Following on from https://github.com/localgovdrupal/localgov_workflows/issues/53, where we've made some good changes to tab names

We're not able to remove the moderated content tab as some councils may be using it

So let's discuss:

- renaming it
- changing the description so its use is more clear
- moving it to the end of the tabs
- providing instructions for a council to hide it locally

**Comment by willguv** [comment]
Is "Pending" a better label for this tab?



![Image](https://github.com/localgovdrupal/localgov_workflows/assets/708140/76fd44e7-6eed-4a17-a500-19c08b43731b)

**Comment by willguv** [comment]
- Call the tab "unpublished"
- Move it to the end of the row
- Wording should "Pages in Draft, Archive and Needs Review states appear here"

Don't worry about toggle to turn on/ off

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_workflows/pull/73

**Comment by willguv** [comment]
Hi @msayoung @stephen-cox is this going to be merged in? Many thanks

**Comment by stephen-cox** [comment]
Hi @willguv - just finishing off https://github.com/localgovdrupal/localgov_workflows/issues/12 which will be ready for review later this week. Will prioritise this once that's done.

**Comment by willguv** [comment]
Would be good to knock this off quickly too @stephen-cox

**Comment by stephen-cox** [comment]
This should be fixed with #88. It's been deployed to the product site for testing.
